project_name: bunnyshell-cli

before:
  hooks:
    - go mod tidy

brews:
  - name: cli
    description: "Bunnyshell's command line tool to create and manage on-demand environments."
    homepage: https://documentation.bunnyshell.com

    tap:
      owner: bunnyshellosi
      name: homebrew-tap
    folder: Formula

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X bunnyshell.com/cli/pkg/build.Version={{.Version}} -X bunnyshell.com/cli/pkg/build.Commit={{.Commit}} -X bunnyshell.com/cli/pkg/build.Date={{time "2006-01-02"}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

announce:
  slack:
    enabled: true
    blocks:
      - type: section
        text:
          type: mrkdwn
          text: |
            A new release was just performed on *CLI*: `{{ .Tag }}`

            Check it out at {{ .ReleaseURL }}
